# Generated by Django 5.2 on 2025-04-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
