# Generated by Django 5.2 on 2025-04-18 20:11

import room_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0002_remove_room_image_room_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, null=True, validators=[room_app.models.validate_image_url]),
        ),
    ]
